import type { Metadata } from "next";
import { Geist, Geist_Mono, Merriweather_Sans, Raleway } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { SideBar } from "@/components/Sidebar";
import { Toaster } from "sonner";
import FloatingChatBot from "./chat/page";

const raleway = Raleway({
  variable: "--display-font",
});

const merriweather = Merriweather_Sans({
  variable: "--body-font",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SidebarProvider className="bg-zinc-800">
        <SideBar />
      <body
        className={`${raleway.variable} ${merriweather.variable}`}
      >
          <SidebarTrigger />
          {children}
          <FloatingChatBot />
          <Toaster position="top-right" richColors />
      </body>
        </SidebarProvider>
    </html>
  );
}
